#include "skin.h"
#include "accessor.h"

#include <iostream>

namespace gltfloader
{

/* **************************** is_joint_unique **************************** */

bool
is_joint_unique (const IndexHelper &helper, const std::vector<int> &joints,
                 size_t i)
{
  if (i >= helper.nodes_size ())
    return true;

  size_t cnt = 0;

  for (auto it : joints)
    {
      if (joints[i] == it)
        cnt++;
    }

  return cnt <= 1;
}

/* *************************** GLTFSkin::GLTFSkin ************************** */

GLTFSkin::GLTFSkin (const std::string &name)
    : GLTFNamedObject (name), m_inverse_bind_matrices (std::nullopt),
      m_skeleton (std::nullopt)
{
  //
}

/* ************************** GLTFSkin::~GLTFSkin ************************** */

GLTFSkin::~GLTFSkin ()
{
  //
}

/* ******************** GLTFSkin::inverse_bind_matrices ******************** */

const std::optional<size_t> &
GLTFSkin::inverse_bind_matrices () const
{
  return m_inverse_bind_matrices;
}

/* *************************** GLTFSkin::skeleton ************************** */

const std::optional<size_t> &
GLTFSkin::skeleton () const
{
  return m_skeleton;
}

/* **************************** GLTFSkin::joints *************************** */

const std::vector<size_t> &
GLTFSkin::joints () const
{
  return m_joints;
}

/* **************************** GLTFSkin::create *************************** */

std::shared_ptr<GLTFSkin>
GLTFSkin::create (const IndexHelper &helper, const std::string &name,
                  const std::optional<int> &inverse_bind_matrices,
                  const std::optional<int> &skeleton,
                  const std::vector<int> &joints)
{
  std::shared_ptr<GLTFSkin> tmp (new GLTFSkin (name));

  size_t shifted_accessor_index;
  size_t shifted_node_index;

  if (inverse_bind_matrices == std::nullopt)
    {
      // NOTE : glTF 2.0 5.28.1 demand that empty inverseBindMatrices must
      // produce identity matrices. Identity matrices will be generated by
      // loader itself.
      tmp->m_inverse_bind_matrices = std::nullopt;
    }
  else
    {
      shifted_accessor_index
          = helper.accessor_defaults_size () + inverse_bind_matrices.value ();
      if (inverse_bind_matrices < 0)
        {
          std::cout << "[W] glTF 2.0 5.28.1: skin.inverseBindMatrices >= 0"
                    << std::endl;
          return nullptr;
        }
      else if (shifted_accessor_index >= helper.accessors_size ())
        {
          std::cout << "[W] glTF 2.0 5.28.1: skin.inverseBindMatrices is out "
                       "of bounds"
                    << std::endl;
          return nullptr;
        }
      else
        {
          if (helper.accessor (shifted_accessor_index)->count ()
              != joints.size ())
            {
              std::cout << "[W] glTF 2.0 5.28.1: skin.inverseBindMatrices "
                           "must point to an accessor with the same number of "
                           "elements as joints"
                        << std::endl;
              return nullptr;
            }
        }
      tmp->m_inverse_bind_matrices = shifted_accessor_index;
    }

  if (skeleton == std::nullopt)
    {
      tmp->m_skeleton = std::nullopt;
      // NOTE : To find out what node is the root node of the skeleton, we need
      // to build a scene tree. Only common parent of all joints can be root.
    }
  else
    {
      shifted_node_index = helper.node_defaults_size () + skeleton.value ();

      if (skeleton < 0)
        {
          std::cout << "[W] glTF 2.0 5.28.2: skin.skeleton >= 0" << std::endl;
          return nullptr;
        }
      else if (shifted_node_index >= helper.nodes_size ())
        {
          std::cout << "[W] glTF 2.0 5.28.2: skin.skeleton is out of bounds"
                    << std::endl;
          return nullptr;
        }
      else
        {
          tmp->m_skeleton = shifted_node_index;
        }
    }

  if (joints.empty ())
    {
      std::cout << "[W] glTF 2.0 5.28.3: skin.joints is empty" << std::endl;
      return nullptr;
    }
  else
    {
      for (size_t i = 0; i < joints.size (); i++)
        {
          if (joints[i] < 0)
            {
              std::cout << "[W] glTF 2.0 5.28.3: skin.joints[" << i << "] >= 0"
                        << std::endl;
              return nullptr;
            }

          if (!is_joint_unique (helper, joints, i))
            {
              std::cout << "[W] glTF 2.0 5.28.3: skin.joints[" << i
                        << "] is not unique" << std::endl;
              return nullptr;
            }
        }
      for (auto it : joints)
        {
          tmp->m_joints.push_back (helper.node_defaults_size () + it);
        }
    }

  return tmp;
}

}